language: python
python:
    - "3.6"
sudo: required
services:
    - docker
install:
    - pip install tox
env:
    - TARGET=test
    - TARGET=itest_trusty
    - TARGET=itest_xenial
    - TARGET=itest_bionic
script:
    - make $TARGET
