name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        make_target:
          - test
          - itest_bionic
          - itest_jammy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install tox
      - run: make ${{ matrix.make_target }}
